on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'main' # Push events to matching v*, i.e. v1.0, v20.15.10
    workflow_dispatch: "workflow_dispatch example"

name: Create Release example

jobs:
  build:
    name: Create Release example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release example
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false